### ISSUE TITLE
Ordnung für das Attribut sn in Suche unterstützen

### ISSUE THREAD

**Issue by thomasDOTwtf** [eventphone/guru3-ldap#1]
Das Gerät "Polycom SoundPoint IP 650" sendet wohl hardcoded einen LDAP-Filter Kriterium mit.

Das kann leider auch nicht abgeschaltet werden:
https://community.polycom.com/t5/VoIP-SIP-Phones/LDAP-filter-sn-gt-0-sn-lt-zz/td-p/108823

Die LDAP-Implementierung hat keine Ordnung auf den "sn" Key definiert und liefert einfach gar kein Ergebniss mehr wenn man (sn>=0) oder (sn<=zz) verwendet:

Reproduzierbar mit folgenden Schritten möglich.
Positiver Fall:
ldapsearch -H ldap://guru3.eventphone.de/ -ZZ -x -b 'ou=rC3 2021 NOWHERE,dc=eventphone,dc=de' -s sub 1.1
Negative Fälle:
ldapsearch -H ldap://guru3.eventphone.de/ -ZZ -x -b 'ou=rC3 2021 NOWHERE,dc=eventphone,dc=de' -s sub '(sn>=0)' 1.1
ldapsearch -H ldap://guru3.eventphone.de/ -ZZ -x -b 'ou=rC3 2021 NOWHERE,dc=eventphone,dc=de' -s sub '(sn<=zz)' 1.1
ldapsearch -H ldap://guru3.eventphone.de/ -ZZ -x -b 'ou=rC3 2021 NOWHERE,dc=eventphone,dc=de' -s sub '(&(sn>=0)(sn<=zz))' 1.1

**Comment by zivillian** [comment]
may be fixed by https://github.com/eventphone/guru3-ldap/commit/599b53dc2b4f3c7e4d3604e03ba4bed08f2bc99c, but currently untested
